MovieManagementSelf/Models/ErrorViewModel.cs
namespace MovieManagementSelf.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

MovieManagementSelf/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace MovieManagementSelf.Controllers
{
	public class BaseController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}

	protected async Task<string> renderViewPartial (string viewName, ICompositeViewEngine _viewEngine, object model = null)
	{
		if (string.IsNullOrEmpty(viewName){
			viewName = ControllerContext.ActionView.ActionName
		})
	}

MovieManagementSelf/Controllers/FileUploadController.cs
using Entity.Common;
using Entity.Model;
using Entity.ViewModel;
using Extensions;
using Helper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace MovieManagementSelf.Controllers
{
	public class FileUploadController : Controller
	{
		[HttpPost]
		public JsonResult UploadFile()
		{
			ResponseData result = new ResponseData();

			try
			{
				var collection = Request.Form.ToDictionary(x => x.Key, x => x.Value.ToString());
				DocumentDetailsVM data = JsonConvert.DeserializeObject<DocumentDetailsVM>(collection["data"]);

				if (Request.Form.Files != null && Request.Form.Files.Count > 0)
				{
					var file = Request.Form.Files[0];

					//string mimeType = file?.ContentType;
					if (file != null)
					{
						if (file.Length / 1048576 > 2)
						{
							result.Message = "File size must be less then 2MB.";
							result.Success = false;
						}
						else
						{
							//xyz.pdf   -> xyz     def     pdf

							var extArray = file.FileName.Split('.');
							string fileExtension;
							if (extArray == null || extArray.Length < 2)
							{
								result.Success = false;
								result.Message = "File has invalid extension.";
								return Json(result);
							}
							fileExtension = extArray[extArray.Length - 1];
							if (string.IsNullOrEmpty(fileExtension))
							{
								result.Success = false;
								result.Message = "File has invalid extension.";
								return Json(result);
							}

							{
								ResponseData fileResult = FileHandler.UploadFile(Guid.NewGuid().ToString() + "." + fileExtension, file);
								if (fileResult.Success)
								{
									var docDetails = new
									{
										DocGuid = fileResult.Data.ToText(),
										DocTypeId = data.DocTypeId,
										MimeType = file.ContentType,
										FileExtension = fileExtension,
										BaseLocation = fileResult.Message
									};
									result.Data = docDetails;
									result.Success = true;
								}
							}
						}
					}
					else
					{
						result.Message = "Uploaded File is not valid";
						result.Success = false;
					}
				}
			}
			catch (Exception ex)
			{
				result.Success = false;
				result.Message = ex.Message;
			}

			return Json(result);
		}

	}
}

MovieManagementSelf/Controllers/GenreInfoController.cs
using Microsoft.AspNetCore.Mvc;
using DAO;
using System.Text.Json;
using Entity.ViewModel;
using Entity.Model;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MovieManagementSelf.Controllers
{
	public class GenreInfoController : Controller
	{
		ApplicationDbContext _context;

		public GenreInfoController(ApplicationDbContext context)
		{
			_context = context;
		}

	
		public IActionResult Index()
		{
			return View();
		}
	}
}

MovieManagementSelf/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MovieManagementSelf.Models;
using System.Diagnostics;

namespace MovieManagementSelf.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

MovieManagementSelf/Controllers/ShowInfoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
namespace MovieManagementSelf.Controllers
{
    public class ShowInfoController : Controller
    {
        ApplicationDbContext _context;

        public ShowInfoController(ApplicationDbContext context)
        {
            _context = context;
        }

        
    
        public IActionResult Index()
        {
            return View();
        }
    }
}

MovieManagementSelf/Controllers/UserGroupController.cs
using Microsoft.AspNetCore.Mvc;
using BAL.Interface;
using Entity.ViewModel;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MovieManagementSelf.Controllers
{
    public class UserGroupController : Controller
    {
        IUserGroupService _iug;

        public UserGroupController(IUserGroupService iug)
        {
            _iug = iug;
        }

        public IActionResult Index()
        {
            var data = _iug.GetActiveUserGroup();
            return View(data);


        }

        [HttpGet]

        public JsonResult GetAllData()
        {
            return Json(new
            {
                Success = true,
                Data = _iug.GetActiveUserGroup()
            });

        }

        [HttpGet]

        public JsonResult Delete(int id)
        {
            var res = _iug.Delete(id);
            return Json(res);
        }

        [HttpGet]

        public JsonResult GetByID(int id)
        {
            var res = _iug.GetByID(id);
            return Json(res);
        }
        [HttpPost]

        public JsonResult Save([FromBody] UserGroupVM vm)
        {
            var res = _iug.Save(vm);
            return Json(res);
        }


        



        }




    }

MovieManagementSelf/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="author" content="Untree.co" />
    <link rel="shortcut icon" href="favicon.png" />

    <meta name="description" content="" />
    <meta name="keywords" content="bootstrap, bootstrap5" />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />

    <link rel="stylesheet" href="/fonts/icomoon/style.css" />
    <link rel="stylesheet" href="/fonts/flaticon/font/flaticon.css" />

    <link rel="stylesheet" href="/css/tiny-slider.css" />
    <link rel="stylesheet" href="/css/aos.css" />
    <link rel="stylesheet" href="/css/style.css" />

    <title>
      Property &mdash; Free Bootstrap 5 Website Template by Untree.co
    </title>
  </head>
  <body>
    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close">
          <span class="icofont-close js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>
    @{
        Html.RenderPartial("_header");
    }

    <div class="body">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
        
        @RenderBody();
    </div>
    <div class="site-footer">
        @{
            Html.RenderPartial("_footer");
        }
    </div>
  
@RenderBody();
    <div id="overlayer"></div>
    <div class="loader">
      <div class="spinner-border" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>



    <script src="js/bootstrap.bundle.min.js"></script>
    <script src="js/tiny-slider.js"></script>
    <script src="js/aos.js"></script>
    <script src="js/navbar.js"></script>
    <script src="js/counter.js"></script>
    <script src="js/custom.js"></script>
  </body>
</html>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="http://nepalidatepicker.sajanmaharjan.com.np/nepali.datepicker/js/nepali.datepicker.v4.0.4.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/2.0.8/js/dataTables.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.2/js/dataTables.buttons.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.dataTables.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.print.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="
https://cdn.jsdelivr.net/npm/block-ui@2.70.1/jquery.blockUI.min.js
"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.4/jquery-confirm.min.js"></script>

    



@RenderSection("Scripts",required:false);

@* @await RenderSectionAsync("Scripts",required:false) *@

MovieManagementSelf/Views/Shared/_footer.cshtml
<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <div class="widget">
                <h3>Contact</h3>
                <address>43 Raymouth Rd. Baltemoer, London 3910</address>
                <ul class="list-unstyled links">
                    <li><a href="tel://11234567890">+1(123)-456-7890</a></li>
                    <li><a href="tel://11234567890">+1(123)-456-7890</a></li>
                    <li>
                        <a href="mailto:info@mydomain.com">info@mydomain.com</a>
                    </li>
                </ul>
            </div>
            <!-- /.widget -->
        </div>
        <!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <div class="widget">
                <h3>Sources</h3>
                <ul class="list-unstyled float-start links">
                    <li><a href="#">About us</a></li>
                    <li><a href="#">Services</a></li>
                    <li><a href="#">Vision</a></li>
                    <li><a href="#">Mission</a></li>
                    <li><a href="#">Terms</a></li>
                    <li><a href="#">Privacy</a></li>
                </ul>
                <ul class="list-unstyled float-start links">
                    <li><a href="#">Partners</a></li>
                    <li><a href="#">Business</a></li>
                    <li><a href="#">Careers</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">FAQ</a></li>
                    <li><a href="#">Creative</a></li>
                </ul>
            </div>
            <!-- /.widget -->
        </div>
        <!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <div class="widget">
                <h3>Links</h3>
                <ul class="list-unstyled links">
                    <li><a href="#">Our Vision</a></li>
                    <li><a href="#">About us</a></li>
                    <li><a href="#">Contact us</a></li>
                </ul>

                <ul class="list-unstyled social">
                    <li>
                        <a href="#"><span class="icon-instagram"></span></a>
                    </li>
                    <li>
                        <a href="#"><span class="icon-twitter"></span></a>
                    </li>
                    <li>
                        <a href="#"><span class="icon-facebook"></span></a>
                    </li>
                    <li>
                        <a href="#"><span class="icon-linkedin"></span></a>
                    </li>
                    <li>
                        <a href="#"><span class="icon-pinterest"></span></a>
                    </li>
                    <li>
                        <a href="#"><span class="icon-dribbble"></span></a>
                    </li>
                </ul>
            </div>
            <!-- /.widget -->
        </div>
        <!-- /.col-lg-4 -->
    </div>
    <!-- /.row -->

    <div class="row mt-5">
        <div class="col-12 text-center">
            <!--
              **==========
              NOTE:
              Please don't remove this copyright link unless you buy the license here https://untree.co/license/
              **==========
            -->

            <p>
                Copyright &copy;
                <script>
                    document.write(new Date().getFullYear());
                </script>
                . All Rights Reserved. &mdash; Designed with love by
                <a href="https://untree.co">Untree.co</a>
                <!-- License information: https://untree.co/license/ -->
            </p>
            <div>
                Distributed by
                <a href="https://themewagon.com/" target="_blank">themewagon</a>
            </div>
        </div>
    </div>
</div>

MovieManagementSelf/Views/Shared/_header.cshtml
<nav class="site-nav">
    <div class="container">
        <div class="menu-bg-wrap">
            <div class="site-navigation">
                <a href="index.html" class="logo m-0 float-start">Property</a>

                <ul class="js-clone-nav d-none d-lg-inline-block text-start site-menu float-end">
                    <li><a href="index.html">Home</a></li>
                    <li class="has-children active">
                        <a href="properties.html">Properties</a>
                        <ul class="dropdown">
                            <li><a href="#">Buy Property</a></li>
                            <li><a href="#">Sell Movies</a></li>
                            <li class="has-children">
                                <a href="#">Dropdown</a>
                                <ul class="dropdown">
                                    <li><a href="#">Sub Menu One</a></li>
                                    <li><a href="#">Sub Menu Two</a></li>
                                    <li><a href="#">Sub Menu Three</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li><a href="services.html">Services</a></li>
                    <li><a href="about.html">Movies</a></li>
                    <li><a href="contact.html">Contact Us</a></li>
                </ul>

                <a href="#"
                   class="burger light me-auto float-end mt-1 site-menu-toggle js-menu-toggle d-inline-block d-lg-none"
                   data-toggle="collapse"
                   data-target="#main-navbar">
                    <span></span>
                </a>
            </div>
        </div>
    </div>
</nav>

MovieManagementSelf/Views/ShowInfo/Index.cshtml
@{
	Layout = null;
}


<div class="row">
	<div class="card">
		<div class="card-body">
			<input type="text" class="txtShowMovie"/>
			<input type="text" class="txt" />
		</div>
	</div>
</div>

MovieManagementSelf/Views/UserGroup/Index.cshtml
@model List<Entity.ViewModel.UserGroupVM>
<h1 class="mt-5">User Group Table</h1>


<div class="row mb-2">
	<div class="col-md-12">
		<div class="card">
		<div class="card-body">
			<div class="row">

				<div class="col-md-3">
					<label>Group Name</label>
					
					<input type="text" class="txtGroupName form-control"/> 
					<input type="hidden" class="hdnUserGroupID form-control" value="0"/>
				</div>
				<div class="col-md-3">
					<label>Group Code</label>
						<input type='text' class="txtGroupCode form-control"/>
				</div>
				<div class="col-md-3">
				
					<button type="button" class="btn btnClear"><i class="fa fa-trash">Clear</i></button>
					<button type="button" class="btn btnNew"><i class="fa fa-plus">Add</i></button>
					</div>

			</div>
			</div>
		
</div>

<div class="modal" id="mdlSetup" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Setup Form</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				</div>
				<div class="modal-body">
					</div class="form-group">
					<label>UserGroupName</label>
					<input type="text" class="form-control" id="txtUserGroupName"/>
					</div>
					<div class="form-group">
						<label>UserGroupCode</label>
						<input type="text" class="form-control" id="txtUserGroupCode"/>
						</div>
				
				</div>
				</div>
				</div>
				
	<div class="row">
		<div class="col-md-12">
	<div class="card">
		<div class="card-body">
			<table class="table table-responsive table-stripped dtTable">
				<thead>
					<tr>
						<th>SN</th>
						<th>Group Name</th>
						<th>Group Code</th>
						<th>Action</th> 
					</tr>
				</thead>
				<tbody class="data-list"></tbody>
			</table>
		</div>
	</div>
</div>

	</div>

@section Scripts{
	<script>

		$(document).ready(function(){
			loadData();
			
		
		});

		function clearForm() {
			$('.txtGroupName').val('');
			$('.txtGroupCode').val('');
			$('.hdnUserGroupID').val(0);
		}
	
		function loadData() {
			$.ajax({
				contentType: 'application/json; charset=utf-8',
				url: '@Url.Action("GetAllData","UserGroup")',
				method: 'GET',
				success: function (res) {
					if (res.success) {
						var allData = res.data;
						var htmls = "";
						var htmls = "<option value = 0></option>"
						
						$.each(allData, function (i, x) {
							htmls += "<option value='" +x.ComplainStatusID+ "'></option>"						
							htmls += "<tr>";
							htmls += "<td>" + (i + 1) + "</td>";
							htmls += "<td>" + x.userGroupName + "</td>";
							htmls += "<td>" + x.userGroupCode + "</td>";
							htmls += "<td>";
							htmls += "<button type='button' class='btnEdit btn btn - secondary btn - sm ' data-key='" + x.userGroupID + "'> Edit </button>";
							htmls += "<button type='button' class='btnDelete btn btn - danger btn - sm' data-key='" + x.userGroupID + "'> Delete </button>"
							htmls += "</td>";
							htmls += "</tr>";
						});
						$('.data-list').html(htmls);
					}
					else {
						alert(res.message);
					}
				},
				error: function (err) {

				},
				beforeSend: function () {
					// $.blockUI();
				},
				complete: function () {

				}
			});

			$(document).on('click', '.btnNew', function () {
				var obj = {
					UserGroupName: $('.txtGroupName').val(),
					UserGroupCode: $('.txtGroupCode').val(),
					UserGroupID: +$('.hdnUserGroupID').val()
				}
				if (!obj.UserGroupName) {
					Swal.fire({
						title:"Oops!",
						text:"Enter your UserGroup Name",
						icon:"Warning"
					})
				}

				else if (!obj.UserGroupCode) {
					Swal.fire({
						title:"Oops!",
						text:"Enter your UserGroup Code",
						icon:"Warning"
					})
				}
				else {
					$.ajax({
						url: '@Url.Action("Save","UserGroup")',
						data: JSON.stringify(obj),
						method: 'POST',
						contentType: 'application/json;charset=utf-8',
						success: function (res) {
							if (res.success) {
								alert(res.message);
								loadData();

							}
							else {
								alert(res.message)
							}
						},
						error: function (err) {
							console.log(err);
						},
						beforeSend: function () {

						},
						complete: function () {
							
						}
					});
				}
			});



			$(document).on('click','.btnClear',function(){
				clearForm();
			})

			$(document).on('click', '.btnDelete', function () {
				var groupid = $(this).data('key');
				var ok = confirm('Are you sure to delete the data?');
				if (ok) {
					$.ajax({
						method: 'GET',
						contentType: 'application/json;charset=utf-8',
						url: '@Url.Action("Delete","UserGroup")?id=' + groupid,
						success: function (res) {
							if (res.success) {
								loadData();
								
							}
							else {
								alert(res.message)
							}
						},
						error: function (err) {
							console.log(err);
						},
						beforeSend: function () {

						},
						complete: function () {

						}
					}
					);
				}
			});

			$(document).on('click', '.btnEdit', function () {
				var groupid = $(this).data('key');
				$.ajax({
					method:'GET',
					contentType:'application/json;utf=charset-8',
					url:'@Url.Action("GetByID","UserGroup")?id=' +groupid,
						success: function(res){
							var allUserData = res.data;
						if(res.success){
							loadData();
							console.log(allUserData);
							$('.txtGroupName').val(allUserData.userGroupName);
							$('.txtGroupCode').val(allUserData.userGroupCode);
							$('.hdnUserGroupID').val(allUserData.userGroupID);
						}
	},
	
	error: function (err) {
						console.log(err);
					},
					beforeSend: function () {
						// $.blockUI();
					},
					complete: function () {
						$.unBlockUI();
					}
				})
	;

			});


		}
		
	</script>
	
	}